name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-and-dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' 

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install 

    - name: Cache Backend Node Modules
      uses: actions/cache@v2
      with:
        path: backend/node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install  

    - name: Cache Frontend Node Modules
      uses: actions/cache@v2
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-frontend-

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build  
