name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for opening your first issue in this repository! I value your contribution and will review it soon. If you have any questions, feel free to ask!"
        pr-message: "Thank you for submitting your first pull request! I appreciate your effort to improve our project. I will review your PR soon. In the meantime, if you have any questions about the process, please feel free to reach out!"

